name: dart_only_riverpod_playground
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  riverpod: ^2.6.1
  # path: ^1.8.0

dev_dependencies:
  custom_lint: ^0.7.5
  lints: ^5.0.0
  riverpod_lint: ^2.6.5
  test: ^1.24.0
